eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    leaseExpirationDurationInSeconds: 5
    leaseRenewalIntervalInSeconds: 5
server:
  port: 9001
spring:
  application:
    name: goods-api